[build]
  publish = "dist/"
  command = "npm run build"
[context.production]
  publish = "dist/"
  command = "npm run build"
[context.deploy-preview]
  publish = "dist/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
